### PR TITLE
add gh-pages deploy script

### PR DESCRIPTION
**Pull request by MaxGraey**

### CODE REVIEW

**Comment by torch2424** [comment]
Awe yeah! 🎉

**Comment by torch2424** [comment]
I know you didn't ask for my review, but I do this exact thing on my projects, I say 🚢 😄

**Comment by MaxGraey** [comment]
Ok, I'll try to merge and see could this works for us

**Comment by dcodeIO** [comment]
btw. this seems to be missing the `gh-pages` module as a dependency

**Comment by MaxGraey** [comment]
I have it installed globally

**Pull request merged**
